steps:
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['pull', 'eu.gcr.io/douglasconnect-docker/edelweiss/develop/csvtoapi:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', 'douglasconnect/orn-registry:latest',
         '--build-arg', 'GIT_CHANGESET=$COMMIT_SHA',
         '-f', 'csvtoapi/Dockerfile',
         '.'
        ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'douglasconnect/orn-registry:latest', 'douglasconnect/orn-registry:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'douglasconnect/orn-registry:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'douglasconnect/orn-registry:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/csvtoapi', 'csvtoapi=douglasconnect/orn-registry:$SHORT_SHA', '--namespace=edelweiss-develop']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-d'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
images: ['douglasconnect/orn-registry:latest', 'douglasconnect/orn-registry:$SHORT_SHA']
