steps:
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['pull', 'eu.gcr.io/douglasconnect-docker/edelweiss/develop/csvtoapi:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', 'douglasconnect/orn-registry:latest',
         '--build-arg', 'GIT_CHANGESET=$COMMIT_SHA',
         '-f', 'csvtoapi/Dockerfile',
         '.'
        ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'douglasconnect/orn-registry:latest', 'douglasconnect/orn-registry:$SHORT_SHA']
images: ['douglasconnect/orn-registry:latest', 'douglasconnect/orn-registry:$SHORT_SHA']
